### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [Sanbroh/prj-rev-bwfs-dasmoto#6]
https://github.com/Sanbroh/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/resources/style.css#L25-L47

There's way too much repetition in these CSS rules.

Use more general selectors to apply your common/shared styles and use more specific selectors to apply your more unique/individual styles, like so:

```css
* {
  font-family: Helvetica;
}

h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

#brushes {
  background-color: mediumspringgreen;
}
```
